### ISSUE TITLE
Plugin Uses very much time per tick

### ISSUE THREAD

**Issue by Sabbelsocke1** [SphinxHD/MySQL-Sync#12]
[MySQL-Sync](censered#) (v1.4.9)
Authors: Sphinx_HD
Syncs Player Data between Servers
MySQL-Sync::Combined Totalcount(211)  total(86.45% 27.24s, 237.90% of tick)avg(129.10ms per - 118.95ms/0.92 per tick)
MySQL-Sync::Task: hd.sphinx.sync.listener.JoinListener$1 (Single)count(6)  total(4.87% 1.535s, 13.41% of tick)avg(255.86ms per - 6.70ms/0.03 per tick)
MySQL-Sync::Event: h.s.s.l.QuitListener (PlayerQuitEvent)count(7)  total(3.19% 1.005s, 8.78% of tick)avg(143.59ms per - 4.39ms/0.03 per tick)
MySQL-Sync::Task: hd.sphinx.sync.backup.BackupHandler$1 (interval:70)count(192)  total(78.27% 24.662s, 215.39% of tick)avg(128.45ms per - 107.69ms/0.84 per tick)
MySQL-Sync::Event: h.s.s.l.JoinListener (PlayerJoinEvent)count(6)  total(0.12% 0.038s, 0.33% of tick)avg(6.28ms per - 0.16ms/0.03 per tick)

That are the Timings from the server

Screenshot of the Timings on request

**Comment by SphinxHD** [comment]
Hello there,

thanks for giving me an insight, in how inperformant my plugin realy is. I am working hard on the newest update, which will run EVERYTHING that can be run asynchronously, async. This will benefit for the performance and also resolve these realy bad timings.

I will let this issue report open, till the plugin runs asynchronously.

~ Leo

**Comment by SphinxHD** [comment]
Hello there,

I have resolved this problem in the newest Update, for more Informations, please read the Changelog.

~ Leo
