### ISSUE TITLE
support Folia

### ISSUE THREAD

**Issue by Q2297045667** [SphinxHD/MySQL-Sync#14]
Hope to support Folia
https://github.com/PaperMC/Folia
Currently, Folia does not have a stable data synchronization plugin

**Comment by SphinxHD** [comment]
Hello there,

I have already worked on that the last few days, and now released it on [Spigot](https://www.spigotmc.org/resources/mysql-sync.101554/update?update=540394).
But thanks for requesting this :D.

~ Leo
