### ISSUE TITLE
MySQL-Sync v1.4.13 | Warning: "MySQL Sync is not up to date." - But there is no newer version available?

### ISSUE THREAD

**Issue by Steve41007** [SphinxHD/MySQL-Sync#16]
Server: Paper 1.20.4 #496
Plugin: MySQL-Sync v1.4.13

Problem: 
Server is warning about plugin not up to date. 
But there is no newer version to download?

"Newest Versions":
- spigotmc.org -> v1.4.13
- github -> v1.4.11

Console Output:
[INFO]: [MySQL-Sync] Enabling MySQL-Sync v1.4.13
[INFO]: [MySQL-Sync] §aConnected to the MySQL
[WARN]: [MySQL-Sync] MySQL Sync is not up to date. Please download the newest version on Spigot: https://www.spigotmc.org/resources/mysql-sync.101554/

**Comment by Steve41007** [comment]
In config.yml it seem not to update the version number when updating the plugin.

My config.yml was created with plugin 1.4.11 and still has:

# Version
# - This is needed for Updating the Plugin right, so don't remove or edit it!
#
version: 1.4.11

**Comment by SphinxHD** [comment]
Hello there,

a quick fix would be to write in the config:
`version: 1.4.13`

~ Leo
