### ISSUE TITLE
Economy 

### ISSUE THREAD

**Issue by Andrei8764** [SphinxHD/MySQL-Sync#9]
Can you add sync for essentials?

**Comment by SphinxHD** [comment]
Hello Andrei8764,

I propably won't add a sync option for essentials BUT a sync for any vault economy will be added in the 1.5 Version of MySQL Sync.

~ Leo

**Comment by DaddyRobLIVE** [comment]
+1 The vault sync is highly necessary
checkout this plugin -> https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/
not here to advertise. It was just the previous plugin I'm using before I switched to yours.
